00:00:00.004082 main     VirtualBox COM Server 6.1.18 r142142 win.amd64 (Jan  7 2021 15:32:19) release log
00:00:00.004085 main     Log opened 2023-01-09T07:16:19.557347600Z
00:00:00.004086 main     Build Type: release
00:00:00.004089 main     OS Product: Windows 10
00:00:00.004090 main     OS Release: 10.0.22623
00:00:00.004091 main     OS Service Pack: 
00:00:00.062543 main     DMI Product Name: 82AU
00:00:00.070737 main     DMI Product Version: Lenovo Legion 5 15IMH05
00:00:00.070743 main     Firmware type: UEFI
00:00:00.071062 main     Secure Boot: VERR_PRIVILEGE_NOT_HELD
00:00:00.071074 main     Host RAM: 8099MB (7.9GB) total, 1628MB available
00:00:00.071077 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.071077 main     Process ID: 8112
00:00:00.071078 main     Package type: WINDOWS_64BITS_GENERIC
00:00:00.137183          VirtualBox: object creation starts
00:00:00.137985          Home directory: 'C:\Users\rajshekar\.VirtualBox'
00:00:00.138250          Installed Drivers:
00:00:00.143365            C:\WINDOWS\system32\DRIVERS\VBoxNetLwf.sys (Version: 6.1.18.42142)
00:00:00.143842            C:\WINDOWS\system32\DRIVERS\VBoxUSBMon.sys (Version: 6.1.18.42142)
00:00:00.144178            C:\WINDOWS\system32\DRIVERS\VBoxDrv.sys (Version: 6.1.18.42142)
00:00:00.157815          Loading settings file "C:\Users\rajshekar\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.168590          usbLibGetDevices: Starting USB device enumeration
00:00:00.168815          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&2fb5cead&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
00:00:00.176878          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&2fb5cead&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 14
00:00:00.179042          usbLibGetDevices: Found 3 USB devices, 0 captured
00:00:00.181217          USB: Unknown USB device detected (idVendor: 0x04f2, idProduct: 0xb6c2)
00:00:00.181249          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0026)
00:00:00.278395          netIfIsWireless: CreateFile on '\\.\{56E43057-F4B4-4424-B7D1-C5FA8F15851C}' failed with rcWin=2 (0x2) - ignoring
00:00:00.279638          netIfIsWireless: CreateFile on '\\.\{9E876001-6C49-4CD5-A254-BE5C5692012D}' failed with rcWin=2 (0x2) - ignoring
00:00:00.280286          netIfIsWireless: CreateFile on '\\.\{328884FC-E2F7-4AB5-B98B-143EA4A71159}' failed with rcWin=2 (0x2) - ignoring
00:00:00.286846          HostDnsMonitor: initializing
00:00:00.293405          HostDnsMonitor: updating information
00:00:00.293924          HostDnsMonitor: old information
00:00:00.293925            no server entries
00:00:00.293926            no domain set
00:00:00.293926            no search string entries
00:00:00.293927          HostDnsMonitor: new information
00:00:00.293927            server 1: 172.21.0.111
00:00:00.293928            server 2: 172.21.0.112
00:00:00.293928            server 3: 172.21.0.113
00:00:00.293928            server 4: 8.8.8.8
00:00:00.293929            domain: rect.com
00:00:00.293929            no search string entries
00:00:00.497381          VD: VDInit finished with VINF_SUCCESS
00:00:00.516499          Loading settings file "C:\Users\rajshekar\VirtualBox VMs\kali linux2020.4\kali linux2020.4.vbox" with version "1.16-windows"
00:00:00.565174          OCI: Local config file 'C:\Users\rajshekar\.VirtualBox\oci_config' does not exist
00:00:00.565450          OCI: Original config file 'C:\Users\rajshekar\.oci\config' does not exist
00:00:00.565453          OCI: Reading profiles finished with status ERROR_SUCCESS
00:00:00.565847          ExtPack: Created cloud provider 'OCI' (hrc=ERROR_SUCCESS)
00:00:00.565919          VirtualBox: object created
00:00:06.691617          Saving settings file "C:\Users\rajshekar\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:06.697061          Saving settings file "C:\Users\rajshekar\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:12.232868 main     VirtualBox: object deletion starts
00:00:12.233163 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\rajshekar\VirtualBox VMs\kali linux2020.4\kali linux2020.4.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:00:12.241352 main     HostDnsMonitor: shutting down ...
00:00:12.241550 main     HostDnsMonitor: shut down
00:00:12.249938 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={d0a0163f-e254-4e5b-a1f2-011cf991c38d} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:00:12.250246 main     VirtualBox: object deleted
